name: Deploy BriefChat Server

on:
  push:
    branches:
      - main
    # paths:
    #   - 'server/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SERVER_HOST }}
          username: root
          key: ${{ secrets.PERSONAL_SERVER_SSH_KEY }}
          port: ${{ vars.SSH_PORT || 22 }}
          script: |
            cd /var/www/production/BriefChat/server
            git pull origin main
            npm install --production
            pm2 restart briefchat-proxy || pm2 start index.js --name briefchat-proxy
